print("                二进制数、八进制数、十六进制数转换成十进制数                  ")
b=input("请输入一串二进制数(0-1):")
o=input("请输入一串八进制数(0-7):")
h=input("请输入一串十六进制数(0-F):")
print("二进制数{}→".format(b),end='')
print("十进制数是:",end='')
print(int(str(b),base=2))
print("八进制数{}→".format(o),end='')
print("十进制数是:",end='')
print(int(str(o),base=8))
print("十六进制数{}→".format(h),end='')
print("十进制数是:",end='')
print(int(str(h),base=16))
